services:
  - type: web
    name: smart_resume_app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run main.py --server.port $PORT --server.address 0.0.0.0
    pythonVersion: 3.10