services:
  - type: web
    name: smart-resume-analyzer
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile  # Make sure this path is correct
    envVars:
      - key: PORT
        value: 8501
